name: Push To Windows VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Copy to host directory
        run: powershell Copy-Item -Path G:\actions-runner\_work\DDD_VMPage\DDD_VMPage\* -Destination C:\inetpub\wwwroot -force
